# Permalinks
permalink:           pretty

# Setup
title:               CEPLN
tagline:	Comissão Especial de Processamento de Linguagem Natural
baseurl:             '/ce-pln/'
paginate:            5

paginate_path: "/blog/page:num/"

plugins: [jekyll-paginate]
