# Permalinks
permalink:           pretty

# Setup
title:               CEPLN
tagline:	Comissão Especial de Processamento de Linguagem Natural
baseurl:             ''
paginate:            5


gems: [jekyll-paginate]
